# Growth Gap Analysis

## Data Import and Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

import os
from pathlib import Path
from dotenv import load_dotenv,find_dotenv

from sqlalchemy import create_engine, text


import warnings
warnings.filterwarnings('ignore')

In [ ]:
env_path =Path.cwd()/"github_repo_cloned"/"india-logistics-hub-optimizer"/".env"
load_dotenv(env_path) 

HOST = os.getenv("DB_HOST")
USER = os.getenv("DB_USER")
PASSWORD = os.getenv("DB_PASSWORD")
PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
OUTPUT_DIR = os.getenv("OUTPUT_DIR")

In [3]:
engine = create_engine(f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}")


def sql(query, engine = engine):
    with engine.connect() as conn:
        df = pd.read_sql(text(query),conn)
    return df

In [4]:
query = 'select * from gsdp_growth'
gsdp = sql(query=query, engine = engine)

query = 'select * from bill_growth'
bill = sql(query = query, engine = engine)

In [5]:
gsdp.head()

               state  18/19-19/20  19/20-20/21  20/21-21/22  21/22-22/23
0     andhra pradesh         5.97         5.70        17.36        13.50
1  arunachal pradesh        18.51         1.67        13.92        13.96
2              assam        12.13        -2.03        21.09        19.86
3              bihar        10.20        -2.51        14.64        15.55
4       chhattisgarh         5.37         2.22        16.52        13.12

In [6]:
bill.head()

               state  18/19-19/20  19/20-20/21  20/21-21/22  21/22-22/23
0  jammu and kashmir        89.54        -0.50        31.49        20.96
1   himachal pradesh       100.47        -7.39        31.71        15.29
2             punjab        92.89        -5.74        39.33        18.82
3         chandigarh        93.95       -14.89        35.10        17.37
4        uttarakhand        95.29       -12.67        26.41        20.08

## Initial Data Check

## Bills Growth

## GSDP Growth

## Comparison